'use client'

import type { Metadata } from "next";
// import localFont from "next/font/local";
// // app/layout.tsx
// import '@fontsource/inter/variable.css'
import "./globals.css";
import Navbar from "./components/landing/navbar";
import { usePathname } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Farm basket",
//   description: "Generated by create next app",
// };

// const inter = 'font-inter';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const pathname = usePathname()
  const isDashboardRouter = pathname.startsWith('/dashboard')
return (
    <html lang="en">
      <body
        /**className={`${geistSans.variable} ${geistMono.variable} antialiased`}**/
        className="font-Poppins   dark:bg-yellow-50 dark:text-black"
      >

        <div>
          <div className="mx-8">
            { !isDashboardRouter && <Navbar />}
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}